### ISSUE TITLE
simple checkout sample

### ISSUE THREAD

**Issue by mostadev** [sebdesign/laravel-viva-payments#10]
when tried to implement simple checkout depending on vivapayments documentation and try to compare to your sample code there is so difference because the simple checkout form just returns "vivaWalletToken" and your code sample is like checkout(Request $request, Order $order)

i need code sample for the route to be able to use this tokens returned from the online form

**Comment by sebdesign** [comment]
Hello,

it seems there is a new documentation portal that I wasn't aware of, so the Simple Checkout isn't covered yet in my documentation.

Here is an simple example of the route to accept the `vivaWalletToken` and create a transaction:

```php
use Illuminate\Http\Request;
use Sebdesign\VivaPayments\Transaction;
use Sebdesign\VivaPayments\VivaException;

Route::post('checkout', function (Request $request, Transaction $transaction) {
    try {
        $response = $transaction->create([
            'PaymentToken' => $request->vivaWalletToken,
        ]);
    } catch (VivaException $e) {
        report($e);

        return back()->withErrors($e->getMessage());
    }

    if ($response->StatusId === Transaction::COMPLETED) {
        $message = 'The transaction has been completed successfully.';
    } else {
        $message = 'The transaction was not completed.';
    }

    return view('order/success', compact('message'));
});

```

Please see transaction statuses documentation for more information about the `StatusId`: https://developer.vivawallet.com/api-reference-guide/payment-api/transaction-statuses-and-types

**Comment by mostadev** [comment]
thanks it worked successfully!
