### ISSUE TITLE
Not redirected back to Viva Wallet

### ISSUE THREAD

**Issue by MadMikeyB** [sebdesign/laravel-viva-payments#13]
Hiya

Thanks for the package!

Using this I'm not being redirected back to Viva Wallet after a payment has been processed.

Are you able to help? Viva Wallet are refusing to support this package.

Thanks,

Mikey

**Comment by sebdesign** [comment]
Sure!

Can you show me some example code? I'm assuming you are using the **Redirect Checkout**.

Have you set you redirection URLs in your account? See the first paragraph here:
https://developer.vivawallet.com/online-checkouts/redirect-checkout/#step-3-confirm-the-transaction

**Comment by MadMikeyB** [comment]
Hi @sebdesign  thanks for the reply

Yes, the URL's are set up in the dashboard under payment sources, the card is charged but I'm not redirected - so I can't even check the "completion" code :)

I know I stripped my code right down to your basic example in the README, I'll get the exact code I'm using for you and put it in here. :)

**Comment by MadMikeyB** [comment]
Hi @sebdesign  - this is my pay method.

```
    /**
     * Send the user to payment gateway
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Order $order
     * @param int $total
     *
     * @return void
     */
    protected function pay($request, $order, $total)
    {
        try {
            $gateway = app(\Sebdesign\VivaPayments\Order::class);
            $total = Money::fromPounds($total);
            if ($order->shippingMethod) {
                $summary = $order->summary . ', Shipping: ' . $order->shippingMethod->title . ' @ £' . $order->shippingMethod->price;
            } else {
                $summary = $order->summary . ', Free Shipping';
            }

            $orderCode = $gateway->create($total->inPence(), [
                'FullName'      => $order->customer->full_name,
                'Email'         => $order->customer->email,
                'SourceCode'    => 'Default',
                'MerchantTrns'  => $order->uuid,
                'CustomerTrns'  => $summary,
            ]);
        } catch (VivaException $e) {
            return back()->withErrors($e->getMessage());
        }

        $checkoutUrl = $gateway->getCheckoutUrl($orderCode);
        return redirect($checkoutUrl);
    }
```

That's working, I get sent to Viva Wallet and I can pay, however I do not get sent back. This is the code which would execute if I were redirected back to the site:

```
    /**
     * Recieve the callback from ~WorldPay~ Viva Wallet
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Sebdesign\VivaPayments\Order  $gateway
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, VivaGateway $gateway)
    {
        dd($request->all()); // I dont reach this
        \Log::channel('viva')->info('Viva Redirect Callback', [$request->all()]);

        try {
            $response = $gateway->get($request->get('orderCode'));
        } catch (VivaException $e) {
            return back()->withErrors($e->getMessage());
        }

        if ($response->StateId == 3) {
            // Code here which deals with internal things such as creating a transaction record and updating order, et al. 


            return redirect()->route('account.orders.show', $order);
        } else {
            switch ($response->StateId) {
                case \Sebdesign\VivaPayments\Order::PENDING:
                    $state = 'The order is pending.';
                    break;
                case \Sebdesign\VivaPayments\Order::EXPIRED:
                    $state = 'The order has expired.';
                    break;
                case \Sebdesign\VivaPayments\Order::CANCELED:
                    $state = 'The order has been canceled.';
                    break;
            }
            \Log::channel('viva')->info('Payment Failed: '. $state);

            return redirect()->back()->with([
                'message' => $state,
            ]);
        }
    }
```

**Comment by sebdesign** [comment]
On the `pay` method, you have set the `SourceCode` parameter to `default`. I don't know if you put that just for this example, but you should use the **numeric** code and not the **name** of the source in your code. I know that in the README I'm using `Default`, and the Developer Portal also uses `Default`, but I'm not sure that's correct.

Also, if the source has production URLs, you can maybe create another source with you local URL, e.g. `https://laravel.test/checkout/complete` and `https://laravel.test/checkout/failure`. I think that if your are using production URLs in your local installation, the redirection won't work.

Then in you `viva.php` configuration file, add `'source' => env('VIVA_SOURCE')`, and in your `.env` file add the source code to `VIVA_SOURCE`. If you do this, don't forget to add `VIVA_SOURCE` to your production `.env` also.

When you are being redirected to the Viva environment in your browser, what are you seeing after the payment is made? If you are not redirected back to your site, is the page just staying there? Can you check this with @matthewrgourd also?

**Comment by MadMikeyB** [comment]
Thanks @sebdesign - let me check on the SourceCode for you.

Regarding the redirect, it takes payment then just says "Thanks for payment" essentially. Hoping it's the SourceCode, as I was unclear on what that should be.

**Comment by MadMikeyB** [comment]
@sebdesign it was the SourceCode. Also, there was an issue with $request->get('OrderCode'). This should now be $request->get('s').

Happy to commit a PR to the Repo to document these little things which could catch people out if you want?

Thanks for the help :)

**Comment by sebdesign** [comment]
I'm glad that was resolved! I's be happy to accept a PR for these things. Maybe we should add the source code as a config (`source_code`) with an a `VIVA_SOURCE_CODE` env, and reflect that in the examples?
