### ISSUE TITLE
Add support Native Checkout V2

### ISSUE THREAD

**Issue by alekseykuleshov** [sebdesign/laravel-viva-payments#16]
Hello,

Viva payments had deprecated V1, they said it's no longer working: https://github.com/VivaPayments/API/issues/1461 . 

You can update your lib using my one which already support Native Checkout V2 https://github.com/alekseykuleshov/viva-php if you want.

**Comment by sebdesign** [comment]
Hello,

I've added support for Native Checkout v2 in the latest release: https://github.com/sebdesign/laravel-viva-payments/releases/tag/v5.0.0

I haven't tested in production, also it's not possible to test it using the demo environment, so only the unit tests are accurate. Let me know if you use it and find any issue.
