### ISSUE TITLE
Card Tokenization API

### ISSUE THREAD

**Issue by pantelispanayiotou** [sebdesign/laravel-viva-payments#18]
Hello, 

i am using the package and it works quite good, thanks! 

However following this link: 
https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/#step-3-generate-one-time-charge-token-using-card-token-optional

i can see that the call is /cards/chargetokens instead of cards/token and the response should be 
`$response->chargeToken`

**Comment by sebdesign** [comment]
Thank for spotting this error!

I didn't have the chance to do integration tests because the charge tokens don't work in the sandbox.

Let me know if anything else doesn't work!
