### ISSUE TITLE
Webhooks 200 Response

### ISSUE THREAD

**Issue by egknight** [sebdesign/laravel-viva-payments#22]
Hello,

Can you explain how to respond properly on the webhooks once you have processed them? I keep getting repeat notifications for the same event, I presume because I am not doing it right.

I have tried with JSON 200, text/plain and a 200 and just a straight return, but the events keep coming (see bottom of the code).

Thanks

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Sebdesign\VivaPayments\WebhookController as BaseController;

class WebhookController extends BaseController
{
    /**
     * Handle a Create Transaction event notification.
     *
     * @param  \Illuminate\Http\Request $request
     */
    protected function handleCreateTransaction(Request $request)
    {
        // Get Event Data
        $event = $request->EventData;

        // Update Order
        $order = \App\Order::updateOrCreate (
            ['unique_trans_id' => $event['MerchantTrns'],
            [
                'value' => $event['Amount'],
                'paid' => true
            ]);

        $order->save();
        // Do more processing...

        // Webhook Processed, now return.

        // return response()->json(['success' => 'success'], 200);
        // return response('Success', 200)->header('Content-Type', 'text/plain');
        return 'Success';
    }
}
```

**Comment by sebdesign** [comment]
Hello, in my projects, I don't return anything at all, so the response is an empty 200.

**Comment by egknight** [comment]
Viva continue to post to my webhook endpoint no matter what I do... I wonder if it's the nature of their demo environment or somehow linked to the TLS 1.2 issue. I will keep tracking in any case, but for now I will close this as I don't have a specific solution and I can't be sure it's in any way related to this package.
