### ISSUE TITLE
Responses transaction , cardIniqueReference cannot be null

### ISSUE THREAD

**Issue by Elliot-putt** [sebdesign/laravel-viva-payments#29]
In the Transaction Class I am getting the above error but only on production. Do you have any idea ?

**Comment by Elliot-putt** [comment]
Just to follow up with this error with more information 'carduniqueReference' is null with google pay and apple pay and throws an exception.

**Comment by sebdesign** [comment]
Thanks for reporting, I will fix this today.

**Comment by Elliot-putt** [comment]
Thanks!

**Comment by sebdesign** [comment]
Fixed by https://github.com/sebdesign/laravel-viva-payments/releases/tag/v6.0.0-alpha.6
