### ISSUE TITLE
Undefined constant Sebdesign\VivaPayments\Client

### ISSUE THREAD

**Issue by seldimi** [sebdesign/laravel-viva-payments#3]
Hey.
I have followed your instructions but Laravel 5.2 to create a native form and it gives me that issue. I have added the JS inside a blade template. If I handwrite the "http://demo.vivapayments.com" it works though.

Any ideas?

**Comment by sebdesign** [comment]
Hi @seldimi,

thank you for reporting this. It was a bug in the documentation, as I haven't tested that example. Let me know if it works by adding `::class` after the `Sebdesign\VivaPayments\Client` part, or if you encounter any other issue.
