### ISSUE TITLE
Unknown named parameter $ServiceId

### ISSUE THREAD

**Issue by AmityTek** [sebdesign/laravel-viva-payments#37]
Hi, 

I am trying to do recurring payment and i have this error.
any idea ?
Thanks

![image](https://github.com/sebdesign/laravel-viva-payments/assets/18656702/cbd2dc26-a401-4ea6-897c-6a19c94d3277)

**Comment by sebdesign** [comment]
I've fixed this in v6.0.3. Please run composer update to resolve this.

**Comment by AmityTek** [comment]
Hello Again :)
still for the same function

![image](https://github.com/sebdesign/laravel-viva-payments/assets/18656702/8f25c7a7-9ae2-4028-bfe8-d9fea92163fd)

**Comment by AmityTek** [comment]
could you try the recurring payment and debug it please  ?
