### ISSUE TITLE
HTTPs

### ISSUE THREAD

**Issue by seldimi** [sebdesign/laravel-viva-payments#4]
The following code does not understand the HTTPS so it brings the wrong URL (http) and application sends mixed-content issue (for demo.viva)

**Comment by sebdesign** [comment]
Thank you for submitting an issue. Do you have an example of the code you are referring to?

**Comment by seldimi** [comment]
![2016-11-02 12_19_18- _ webexpert client portal](https://cloud.githubusercontent.com/assets/4827399/19925030/f0cb030c-a0f6-11e6-81b1-12e9831a01d6.jpg)
![2016-11-02 12_19_29- _ webexpert client portal](https://cloud.githubusercontent.com/assets/4827399/19925028/f0c4bdda-a0f6-11e6-964d-bd9d05fe757b.jpg)
![2016-11-02 12_15_55-phpdesigner 8 - ftp___seldimi server10 cretaforce gr_21_webexpert gr_www_client](https://cloud.githubusercontent.com/assets/4827399/19925029/f0c7142c-a0f6-11e6-884c-58dbe5cce62e.jpg)

The issue is described above... a fix is below (on src/Client.php)
![2016-11-02 12_16_04-phpdesigner 8 - ftp___seldimi server10 cretaforce gr_21_webexpert gr_www_client](https://cloud.githubusercontent.com/assets/4827399/19925053/fe792eac-a0f6-11e6-93f1-242741373502.jpg)

**Comment by sebdesign** [comment]
The error on your console suggests that the installments check is performed with XMLHttpRequest (AJAX). This request is performed from the Native Checkout script (client side), not the PHP client (server side).

In the [example](https://github.com/sebdesign/laravel-viva-payments#display-the-payment-form) in the README the script uses the **http** scheme.

`<script src="http://demo.vivapayments.com/web/checkout/js"></script>`

Can you try to change the scheme to **https**?
`<script src="https://demo.vivapayments.com/web/checkout/js"></script>`

**Comment by seldimi** [comment]
As said above, I fixed the above issue by changing Client.php from http://demo to //demo
So maybe that s a fix for everyone trying to test using https than http?

**Comment by sebdesign** [comment]
Actually you're right, the `baseURL` property is passed from the server side.
I will fix this in the afternoon. Meanwhile, you can hardcode the demo url in your script.

`baseURL: 'https://demo.vivapayments.com'`

**Comment by seldimi** [comment]
Thank... next issue probably again on http or something similar, my form works correclty and make installments etc but when I submit it I get error on vivaCheckOut

Client error: `POST http://demo.vivapayments.com/api/orders/` resulted in a `401 Unauthorized` response:
{"Message":"Authorization has been denied for this request."}

I used your CheckOut controller example and only changed my SourceCode

**Comment by sebdesign** [comment]
Have you defined your credentials in the `config/services.php` and your `.env` correctly?

**Comment by wislem** [comment]
I'll raise a small issue here.

Changed it to https://demo.. as you proposed, but upon redirecting to the demo payment page using Firefox or IE, they returned me to the same checkout page but with GET instead of POST.

Changing both urls to //demo... makes it work for Firefox and IE, but it redirects to http instead of https.

FYI to those who might have hit the same wall.
