### ISSUE TITLE
Class Order does not exist

### ISSUE THREAD

**Issue by Stelikas** [sebdesign/laravel-viva-payments#40]
Hello, I'm facing the issue below when trying to access the Order class with the code below.

        $order = app(Sebdesign\VivaPayments\Order::class);

        $orderCode = $order->create($order->total, [
            'fullName'      => $order->patient_fullname,
            'email'         =>  $order->user_email,
            'sourceCode'    => 'Default',
            'merchantTrns'  => 'Ραντεβού: #'.$order->id,
            'customerTrns'  => $order->product_name,
            'customer'      =>  (object) [
                'email'       => $order->user_email,
                'fullName'    => $order->patient_fullname,
                'countryCode' => $countryCode,
                'requestLang' => $requestLang,
            ]
        ]);
```

"Class App\Http\Controllers\Sebdesign\VivaPayments\Order does not exist"

laravel-viva-payments version 5.3

**Comment by sebdesign** [comment]
If you use the FQCN for the `Order` class, you need to add a backslash before:

```php
$order = app(\Sebdesign\VivaPayments\Order::class);
```
