### ISSUE TITLE
Https error

### ISSUE THREAD

**Issue by vaggelis2018** [sebdesign/laravel-viva-payments#5]
Hello and thanks for the great package. 
When we turn website to https package stops working because of the 
'curl' => [
      CURLOPT_SSL_CIPHER_LIST => 'TLSv1',
 ],

in VivaPaymentServiceProvider.php

The only way we managed to make it work is to comment it out. Is there a better way to fix it?

**Comment by sebdesign** [comment]
Thank you for your kind words.

I will look into this issue tonight. It seems TLS v1 has been disabled because it's unsecure. I will check the Viva API and fix this.

**Comment by sebdesign** [comment]
According to https://github.com/VivaPayments/API/issues/497, there is a condition where TLSv1 shouldn't be used, so I adjusted that in v3.0.1. Please update and let me know if it works. Thanks!

**Comment by vaggelis2018** [comment]
It worked perfectly. Thanks for your instant response!
