### ISSUE TITLE
Differences between demo and production

### ISSUE THREAD

**Issue by vaggelis2018** [sebdesign/laravel-viva-payments#6]
Hello again, 
I encountered a new weird issue between demo and production behavior but i am not sure if this happens because of Viva or something else.

The issue is that in demo when i am requesting a token like this with wrong data: 
```
public function requestToken(array $data) : array
	{
		$card = app(\Sebdesign\VivaPayments\Card::class);

		try{
			$token = $card->token(
				$data['CardHolderName'],
				$data['Number'],
				$data['CVC'],
				$data['Month'],
				$data['Year']);

			return ['success' => true, 'token' => $token];

		}catch (\Exception $e){
			return ['success' => false, 'message' => __('paymentForm.failed')];
		}
	} 
```
It works perfectly. In production this not happens. I am assuming that no exception is thrown. Could you inform me if this happens because of a configuration between production laravel settings or package settings or there are differences between viva responses?

Thanks in regards.

*I have already contacted with viva and i am waiting a response from them too regarding their responses on demo and production.

**Comment by sebdesign** [comment]
Hello again,

Assuming no exception is thrown on production, what response are you getting on the `$token`?
Generally the `Sebdesign\VivaPayments\VivaException` is thrown if the response object contains an `ErrorCode` attribute that is not `0`. So in your case the response has a `Token` attribute (which is the `$token`) but no ErrorCode. This is probably something related to the Viva API. Let me know if you get an answer from them.

Thanks.

**Comment by vaggelis2018** [comment]
Sorry for the false alarm it was my fault in the return type of the function with the try catch block .  Thanks for the instant response.
